(** Selection script for the committed broad-3000-2010-01-01 universe fixture.

    Emits
    [trading/test_data/backtest_scenarios/universes/broad-3000-2010-01-01.sexp]
    — a Pinned-shape sexp with up to [TARGET_SIZE] symbols (default 3000),
    sourced alphabetically from [data/sectors.csv]. The as-of date 2010-01-01 is
    a documentation marker telling the runner the intended backtest-window
    start; the file does not encode per-symbol delisting metadata itself.

    Selection rules (deterministic):
    + Read [data/sectors.csv] via {!Sector_map.load}. The committed snapshot has
      ~10,472 (symbol, GICS sector) pairs.
    + Sort alphabetically by symbol.
    + Take the first [TARGET_SIZE] (default 3000).
    + Emit {!Universe_file.Pinned} sexp.

    Per [memory/project_broad_universe_semantics.md] this script does NOT
    pre-filter by bar coverage. Symbols with no cached bars at runtime are
    skipped by the runner's per-symbol path (existing behaviour). This keeps the
    universe survivorship-honest at the membership level — late-start IPOs and
    bars-only-up-to-delisting symbols are both included.

    Per-symbol [Daily_price.active_through] (PR #1076 / #1094) carries the
    delisting marker downstream. The [Pinned] sexp's role is membership only;
    survivorship-aware behaviour is opted into via
    [weinstein_strategy_config.enable_pi_filter] (PR #1089), which reads
    [active_through] through the snapshot pipeline.

    This script is not run from CI or [dune runtest]. It produces the committed
    fixture; the fixture is the source of truth for tests. *)

open Core
module Universe_file = Scenario_lib.Universe_file

(* Cardinality cap. 3000 matches the Russell 3000 in size, though this
   universe is NOT a true Russell 3000 reconstitution — see header
   docstring. *)
let _default_target_size = 3000

(* Minimum-cardinality sanity gate. Stops the script emitting an empty or
   near-empty fixture if [data/sectors.csv] failed to load. *)
let _min_emitted = 1000

(* Hard-coded output path under [trading/test_data/]. Caller [cd]s to the
   workspace root. *)
let _output_path =
  "trading/test_data/backtest_scenarios/universes/broad-3000-2010-01-01.sexp"

let _env_or default key =
  match Sys.getenv key with
  | Some v when String.length v > 0 -> v
  | _ -> default

let _parse_int_env key default =
  try Int.of_string (_env_or (Int.to_string default) key)
  with _ ->
    eprintf "Warning: invalid int in %s; using default %d\n" key default;
    default

let _entries_of_sector_map ~sector_map ~target_size =
  let sorted =
    Hashtbl.to_alist sector_map
    |> List.sort ~compare:(fun (a, _) (b, _) -> String.compare a b)
  in
  List.take sorted target_size
  |> List.map ~f:(fun (symbol, sector) -> { Universe_file.symbol; sector })

let _header_lines ~target_size ~emitted =
  [
    ";; Broad-3000 universe — as-of 2010-01-01.";
    ";;";
    sprintf ";; %d symbols (target: %d), sourced alphabetically from" emitted
      target_size;
    ";; data/sectors.csv. Generated by";
    ";; \
     trading/backtest/scenarios/pick_broad_3000_universe/pick_broad_3000.exe.";
    ";;";
    ";; Membership scope: this is NOT a true Russell 3000 historical";
    ";; reconstitution. The committed sectors.csv is a 2026-04-14";
    ";; snapshot — using it directly is forward-looking-biased at the";
    ";; membership level (symbols dead before 2010 are absent; symbols";
    ";; that IPO'd post-2010 are included). True PI-aware membership";
    ";; reconstitution requires Norgate (vendor signup pending) or";
    ";; iShares IWV-history scraping — both deferred per";
    ";; dev/notes/next-session-priorities-2026-05-15.md §P0 Phase 1.";
    ";;";
    ";; Per-symbol delisting awareness flows through";
    ";; Daily_price.active_through (PRs #1076 / #1094) via the snapshot";
    ";; pipeline, and is opt-in via";
    ";; weinstein_strategy_config.enable_pi_filter = true (PR #1089).";
    ";;";
    ";; No bar-coverage pre-filter applied per";
    ";; memory/project_broad_universe_semantics.md: late-start / early-";
    ";; termination symbols stay in the membership list, and the runner";
    ";; skips per-symbol when no bars are available on a given day.";
    ";;";
  ]

let _write_universe path entries ~target_size =
  let sexp = Universe_file.sexp_of_t (Universe_file.Pinned entries) in
  let header =
    String.concat ~sep:"\n"
      (_header_lines ~target_size ~emitted:(List.length entries))
  in
  Out_channel.with_file path ~f:(fun oc ->
      Out_channel.output_string oc header;
      Out_channel.output_string oc "\n";
      Out_channel.output_string oc (Sexp.to_string_hum sexp);
      Out_channel.output_string oc "\n");
  printf "Wrote %d symbols to %s\n" (List.length entries) path

let main () =
  let data_dir = Data_path.default_data_dir () in
  let target_size =
    _parse_int_env "BROAD_3000_TARGET_SIZE" _default_target_size
  in
  printf "Data dir: %s\n" (Fpath.to_string data_dir);
  printf "Target size: %d\n" target_size;
  let sector_map = Sector_map.load ~data_dir in
  printf "Sector map: %d symbols loaded\n" (Hashtbl.length sector_map);
  let entries = _entries_of_sector_map ~sector_map ~target_size in
  let emitted = List.length entries in
  if emitted < _min_emitted then (
    eprintf
      "Only %d symbols available from sector map (minimum %d); aborting.\n"
      emitted _min_emitted;
    Stdlib.exit 1);
  _write_universe _output_path entries ~target_size

let () = main ()
