((audit_records
  (((entry
     ((symbol AAPL) (entry_date 2019-06-21) (position_id AAPL-wein-61)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (621.8)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.017967958275741824) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.7052120350790312)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Strong)
      (cascade_score 65) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume"
        "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 211.17) (suggested_stop 194.2764)
      (installed_stop 163.4592) (stop_floor_kind Support_floor)
      (risk_pct 0.079999999999999974) (initial_position_value 130291.89)
      (initial_risk_dollars 29437.563599999987)
      (alternatives_considered
       (((symbol APH) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CE) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol EIX) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ETN) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol KEY) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NKE) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol PPG) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol PPL) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ROST) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADBE) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol D) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LIN) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NI) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol O) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ORCL) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol RTX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TJX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol EW) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol ADSK) (entry_date 2019-12-06) (position_id ADSK-wein-345)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (755.7)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.02385495098027543) (rs_trend (Positive_flat))
      (rs_value (1.0514827003576168))
      (volume_quality ((Adequate 1.9942184369654112)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Strong)
      (cascade_score 75) (cascade_grade A) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume" "RS positive"
        "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 179.84) (suggested_stop 165.4528)
      (installed_stop 175.875) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.080000000000000043) (initial_position_value 146389.76)
      (initial_risk_dollars 3227.5100000000029)
      (alternatives_considered
       (((symbol BIIB) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DHR) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DIS) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol GE) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol HPQ) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol KHC) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol LLY) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol SCHW) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ABT) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CRM) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol EA) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GD) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol HCA) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol IFF) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol JNJ) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NSC) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ORCL) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol ADSK) (exit_date 2019-12-12) (position_id ADSK-wein-345)
       (exit_trigger (Stop_loss (stop_price 175.875) (actual_price 175.32)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 5) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.12526076325145258)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol AIG) (entry_date 2019-05-31) (position_id AIG-wein-3)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.011105576363340398) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.9574401798578074)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory)) (sector_name Financials)
      (sector_rating Neutral) (cascade_score 57) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 45.53) (suggested_stop 41.887600000000006)
      (installed_stop 44.375) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.079999999999999891) (initial_position_value 124979.85)
      (initial_risk_dollars 3170.4750000000031)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol AIG) (exit_date 2019-12-03) (position_id AIG-wein-3)
       (exit_trigger (Stop_loss (stop_price 50.95395) (actual_price 50.34)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage3 (weeks_topping 156))) (rs_trend_at_exit ())
       (distance_from_ma_pct -0.054319820809351327)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol AKAM) (entry_date 2019-05-31) (position_id AKAM-wein-4)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0050460021432392329) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.4689795081285717)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Neutral)
      (cascade_score 57) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 74.45) (suggested_stop 68.494)
      (installed_stop 70.875) (stop_floor_kind Support_floor)
      (risk_pct 0.080000000000000043) (initial_position_value 124927.1)
      (initial_risk_dollars 5998.8500000000049)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol AMCR) (entry_date 2019-05-31) (position_id AMCR-wein-5)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0065023000855194109) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 3.5265658747300215)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory)) (sector_name Materials)
      (sector_rating Neutral) (cascade_score 57) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 11.14) (suggested_stop 10.248800000000001)
      (installed_stop 10.908287999999999) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.07999999999999996) (initial_position_value 124990.8)
      (initial_risk_dollars 2599.8086400000188)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol AMCR) (exit_date 2019-06-13) (position_id AMCR-wein-5)
       (exit_trigger
        (Stop_loss (stop_price 10.908287999999999) (actual_price 10.79)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 11) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.02425192265333883)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol ARE) (entry_date 2019-05-31) (position_id ARE-wein-6)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0073776506854955) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.3563410986793505)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory)) (sector_name "Real Estate")
      (sector_rating Neutral) (cascade_score 57) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 144.82) (suggested_stop 133.2344)
      (installed_stop 141.80774399999999) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.08) (initial_position_value 124979.65999999999)
      (initial_risk_dollars 2599.5769280000068)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol ARE) (exit_date 2019-06-26) (position_id ARE-wein-6)
       (exit_trigger
        (Stop_loss (stop_price 141.80774399999999) (actual_price 137.44)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 22) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct -0.013487128460633421)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol CAG) (entry_date 2019-12-20) (position_id CAG-wein-382)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (743.6)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.01852212773372193) (rs_trend (Positive_flat))
      (rs_value (1.1763218820113468))
      (volume_quality ((Strong 3.4140468852425507)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Consumer Staples") (sector_rating Strong)
      (cascade_score 85) (cascade_grade A_plus) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume" "RS positive"
        "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 31.99) (suggested_stop 29.4308)
      (installed_stop 31.324607999999994) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.0799999999999999) (initial_position_value 152272.4)
      (initial_risk_dollars 3167.26592000002)
      (alternatives_considered
       (((symbol MNST) (side Long) (score 85) (grade A_plus)
         (reason_skipped Insufficient_cash))
        ((symbol AMCR) (side Long) (score 75) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ACN) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ADBE) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DHR) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DIS) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol GILD) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol HPQ) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol LLY) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol NOW) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol BDX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol BSX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol EIX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol JNJ) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol MMM) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol MO) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol OMC) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol PEP) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol CPRT) (entry_date 2019-05-31) (position_id CPRT-wein-7)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.016706663409446747) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.2075379344101811)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory)) (sector_name Industrials)
      (sector_rating Neutral) (cascade_score 57) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 64.4) (suggested_stop 59.248000000000005)
      (installed_stop 62.875) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.080000000000000016)
      (initial_position_value 124936.00000000001)
      (initial_risk_dollars 2958.5000000000109)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol D) (entry_date 2019-06-14) (position_id D-wein-41)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (618.6)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0069517977698038969) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.2240910000356728)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name Utilities) (sector_rating Strong) (cascade_score 75)
      (cascade_grade A) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume" "Clean overhead"
        "Strong sector"))
      (side Long) (suggested_entry 77.89) (suggested_stop 71.6588)
      (installed_stop 76.269888) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.080000000000000016) (initial_position_value 129219.51)
      (initial_risk_dollars 2687.76580800001)
      (alternatives_considered
       (((symbol ORLY) (side Long) (score 75) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol TJX) (side Long) (score 75) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DLR) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NI) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol O) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol DAL) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ED) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol KMB) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol TMUS) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol ADSK) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol AMD) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol ATO) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CME) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CSCO) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol DG) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol EL) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol D) (exit_date 2019-06-17) (position_id D-wein-41)
       (exit_trigger (Stop_loss (stop_price 76.269888) (actual_price 75.64)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 2) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.026194749960050966)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol GILD) (entry_date 2019-06-28) (position_id GILD-wein-81)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (637.2)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0076023545605517634) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.5732883150633803)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory)) (sector_name "Health Care")
      (sector_rating Strong) (cascade_score 65) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume"
        "Virgin territory" "Strong sector"))
      (side Long) (suggested_entry 73.26) (suggested_stop 67.399200000000008)
      (installed_stop 71.736192) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.07999999999999996) (initial_position_value 130769.1)
      (initial_risk_dollars 2719.9972800000046)
      (alternatives_considered
       (((symbol ADBE) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CAG) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol D) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol KDP) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LEN) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol O) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ORCL) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol RTX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TJX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ED) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol TMUS) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol ADSK) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol APH) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol ATO) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CMCSA) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol COST) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CSCO) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol CSX) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol DAL) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol GILD) (exit_date 2019-07-01) (position_id GILD-wein-81)
       (exit_trigger (Stop_loss (stop_price 71.736192) (actual_price 67.28)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 2) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.034244251038133666)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol IR) (entry_date 2019-05-31) (position_id IR-wein-8)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.018993452786903779) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 5.3318713373276188)))
      (resistance_quality (Moderate_resistance))
      (support_quality (Virgin_territory)) (sector_name Industrials)
      (sector_rating Neutral) (cascade_score 57) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Moderate resistance"))
      (side Long) (suggested_entry 28.7) (suggested_stop 26.404)
      (installed_stop 27.875) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.079999999999999974) (initial_position_value 124988.5)
      (initial_risk_dollars 3592.8749999999968)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol NOW) (entry_date 2019-12-13) (position_id NOW-wein-365)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (744.1)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0087281031289732913) (rs_trend (Positive_flat))
      (rs_value (0.99108072775699607))
      (volume_quality ((Strong 3.4767844131351913)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Strong)
      (cascade_score 85) (cascade_grade A_plus) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume" "RS positive"
        "Virgin territory" "Strong sector"))
      (side Long) (suggested_entry 304.69) (suggested_stop 280.3148)
      (installed_stop 298.352448) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.080000000000000016) (initial_position_value 148688.72)
      (initial_risk_dollars 3092.7253760000081)
      (alternatives_considered
       (((symbol PRU) (side Long) (score 75) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ADBE) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DHR) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol DIS) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol GE) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol HPQ) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol KHC) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol LLY) (side Long) (score 70) (grade A)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CRM) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol EIX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol IFF) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol MET) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NSC) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol WBD) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol APD) (side Long) (score 52) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_
     (((symbol NOW) (exit_date 2019-12-16) (position_id NOW-wein-365)
       (exit_trigger
        (Stop_loss (stop_price 298.352448) (actual_price 274.11)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 2) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.058094337072140782)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol NXPI) (entry_date 2019-07-05) (position_id NXPI-wein-101)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (643.7)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.019642201486336362) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.1188742045448015)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Strong)
      (cascade_score 75) (cascade_grade A) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume"
        "Virgin territory" "Strong sector"))
      (side Long) (suggested_entry 109.05)
      (suggested_stop 100.32600000000001) (installed_stop 83.7696)
      (stop_floor_kind Support_floor) (risk_pct 0.0799999999999999)
      (initial_position_value 133259.1) (initial_risk_dollars 30892.6488)
      (alternatives_considered
       (((symbol PCG) (side Long) (score 65) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ORCL) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TJX) (side Long) (score 60) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol DAL) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol DLR) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol EIX) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol ETN) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol EW) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol GILD) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol JNJ) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol KEY) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))
        ((symbol PPG) (side Long) (score 50) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol QCOM) (entry_date 2019-05-31) (position_id QCOM-wein-1)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0067693239188561516) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 5.0650537705922511)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Neutral)
      (cascade_score 65) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume" "Clean overhead"))
      (side Long) (suggested_entry 64.66) (suggested_stop 59.4872)
      (installed_stop 62.1696) (stop_floor_kind Support_floor)
      (risk_pct 0.079999999999999932) (initial_position_value 124987.78)
      (initial_risk_dollars 4813.9431999999879)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))
   ((entry
     ((symbol SNPS) (entry_date 2019-05-31) (position_id SNPS-wein-2)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (564.9)"))
        ((name NH-NL) (signal Neutral) (weight 1.5)
         (detail "Index flat over 3 months (NH-NL proxy neutral)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0091961847434345722) (rs_trend ()) (rs_value ())
      (volume_quality ((Strong 2.4576078605647194)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Neutral)
      (cascade_score 65) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Strong volume" "Clean overhead"))
      (side Long) (suggested_entry 119.83) (suggested_stop 110.2436)
      (installed_stop 109.38239999999999) (stop_floor_kind Support_floor)
      (risk_pct 0.079999999999999988) (initial_position_value 124982.69)
      (initial_risk_dollars 10896.846800000008)
      (alternatives_considered
       (((symbol KMB) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol LMT) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol META) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol VMC) (side Long) (score 57) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ADP) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol AZO) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CMG) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol GIS) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol NOC) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol TGT) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol ULTA) (side Long) (score 55) (grade B)
         (reason_skipped Insufficient_cash))
        ((symbol CDNS) (side Long) (score 47) (grade C)
         (reason_skipped Insufficient_cash))))))
    (exit_ ()))))
 (cascade_summaries
  (((date 2018-11-09) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-16) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-23) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-30) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-07) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-14) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-21) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-28) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-04) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-11) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-18) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-25) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-01) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-08) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-15) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-22) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-01) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-08) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-15) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-22) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-29) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-05) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-12) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-26) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-03) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-10) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-17) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-24) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-31) (total_stocks 134) (candidates_after_held 134)
    (macro_trend Bullish) (long_macro_admitted 134)
    (long_breakout_admitted 29) (long_sector_admitted 29)
    (long_grade_admitted 29) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 8))
   ((date 2019-06-07) (total_stocks 195) (candidates_after_held 187)
    (macro_trend Bullish) (long_macro_admitted 187)
    (long_breakout_admitted 63) (long_sector_admitted 63)
    (long_grade_admitted 59) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-06-14) (total_stocks 204) (candidates_after_held 197)
    (macro_trend Bullish) (long_macro_admitted 197)
    (long_breakout_admitted 66) (long_sector_admitted 66)
    (long_grade_admitted 63) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-06-21) (total_stocks 203) (candidates_after_held 196)
    (macro_trend Bullish) (long_macro_admitted 196)
    (long_breakout_admitted 77) (long_sector_admitted 77)
    (long_grade_admitted 76) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-06-28) (total_stocks 192) (candidates_after_held 185)
    (macro_trend Bullish) (long_macro_admitted 185)
    (long_breakout_admitted 44) (long_sector_admitted 44)
    (long_grade_admitted 44) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-07-05) (total_stocks 205) (candidates_after_held 198)
    (macro_trend Bullish) (long_macro_admitted 198)
    (long_breakout_admitted 13) (long_sector_admitted 13)
    (long_grade_admitted 13) (long_top_n_admitted 13)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-07-12) (total_stocks 222) (candidates_after_held 214)
    (macro_trend Bullish) (long_macro_admitted 214)
    (long_breakout_admitted 14) (long_sector_admitted 14)
    (long_grade_admitted 14) (long_top_n_admitted 14)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-07-19) (total_stocks 225) (candidates_after_held 217)
    (macro_trend Bullish) (long_macro_admitted 217)
    (long_breakout_admitted 12) (long_sector_admitted 12)
    (long_grade_admitted 12) (long_top_n_admitted 12)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-07-26) (total_stocks 232) (candidates_after_held 224)
    (macro_trend Bullish) (long_macro_admitted 224)
    (long_breakout_admitted 10) (long_sector_admitted 10)
    (long_grade_admitted 10) (long_top_n_admitted 10)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-02) (total_stocks 230) (candidates_after_held 222)
    (macro_trend Bullish) (long_macro_admitted 222)
    (long_breakout_admitted 10) (long_sector_admitted 10)
    (long_grade_admitted 10) (long_top_n_admitted 10)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-09) (total_stocks 223) (candidates_after_held 215)
    (macro_trend Bullish) (long_macro_admitted 215)
    (long_breakout_admitted 12) (long_sector_admitted 12)
    (long_grade_admitted 12) (long_top_n_admitted 12)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-16) (total_stocks 218) (candidates_after_held 210)
    (macro_trend Bullish) (long_macro_admitted 210)
    (long_breakout_admitted 7) (long_sector_admitted 7)
    (long_grade_admitted 7) (long_top_n_admitted 7) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-23) (total_stocks 227) (candidates_after_held 220)
    (macro_trend Bullish) (long_macro_admitted 220)
    (long_breakout_admitted 5) (long_sector_admitted 5)
    (long_grade_admitted 5) (long_top_n_admitted 5) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-30) (total_stocks 230) (candidates_after_held 223)
    (macro_trend Bullish) (long_macro_admitted 223)
    (long_breakout_admitted 6) (long_sector_admitted 6)
    (long_grade_admitted 6) (long_top_n_admitted 6) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-06) (total_stocks 229) (candidates_after_held 221)
    (macro_trend Bullish) (long_macro_admitted 221)
    (long_breakout_admitted 5) (long_sector_admitted 5)
    (long_grade_admitted 5) (long_top_n_admitted 5) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-13) (total_stocks 202) (candidates_after_held 194)
    (macro_trend Bullish) (long_macro_admitted 194)
    (long_breakout_admitted 8) (long_sector_admitted 8)
    (long_grade_admitted 8) (long_top_n_admitted 8) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-20) (total_stocks 198) (candidates_after_held 191)
    (macro_trend Bullish) (long_macro_admitted 191)
    (long_breakout_admitted 12) (long_sector_admitted 12)
    (long_grade_admitted 12) (long_top_n_admitted 12)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-27) (total_stocks 190) (candidates_after_held 183)
    (macro_trend Bullish) (long_macro_admitted 183)
    (long_breakout_admitted 14) (long_sector_admitted 14)
    (long_grade_admitted 14) (long_top_n_admitted 14)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-04) (total_stocks 201) (candidates_after_held 194)
    (macro_trend Bullish) (long_macro_admitted 194)
    (long_breakout_admitted 11) (long_sector_admitted 11)
    (long_grade_admitted 11) (long_top_n_admitted 11)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-11) (total_stocks 213) (candidates_after_held 205)
    (macro_trend Bullish) (long_macro_admitted 205)
    (long_breakout_admitted 10) (long_sector_admitted 10)
    (long_grade_admitted 10) (long_top_n_admitted 10)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-18) (total_stocks 217) (candidates_after_held 209)
    (macro_trend Bullish) (long_macro_admitted 209)
    (long_breakout_admitted 9) (long_sector_admitted 9)
    (long_grade_admitted 8) (long_top_n_admitted 8) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-25) (total_stocks 202) (candidates_after_held 195)
    (macro_trend Bullish) (long_macro_admitted 195)
    (long_breakout_admitted 6) (long_sector_admitted 6)
    (long_grade_admitted 6) (long_top_n_admitted 6) (short_macro_admitted 0)
    (short_breakdown_admitted 0) (short_sector_admitted 0)
    (short_rs_hard_gate_admitted 0) (short_grade_admitted 0)
    (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-01) (total_stocks 181) (candidates_after_held 174)
    (macro_trend Bullish) (long_macro_admitted 174)
    (long_breakout_admitted 10) (long_sector_admitted 10)
    (long_grade_admitted 10) (long_top_n_admitted 10)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-08) (total_stocks 183) (candidates_after_held 175)
    (macro_trend Bullish) (long_macro_admitted 175)
    (long_breakout_admitted 14) (long_sector_admitted 14)
    (long_grade_admitted 14) (long_top_n_admitted 14)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-15) (total_stocks 193) (candidates_after_held 185)
    (macro_trend Bullish) (long_macro_admitted 185)
    (long_breakout_admitted 19) (long_sector_admitted 19)
    (long_grade_admitted 19) (long_top_n_admitted 19)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-22) (total_stocks 197) (candidates_after_held 190)
    (macro_trend Bullish) (long_macro_admitted 190)
    (long_breakout_admitted 18) (long_sector_admitted 18)
    (long_grade_admitted 18) (long_top_n_admitted 18)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-29) (total_stocks 197) (candidates_after_held 190)
    (macro_trend Bullish) (long_macro_admitted 190)
    (long_breakout_admitted 22) (long_sector_admitted 22)
    (long_grade_admitted 22) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-12-06) (total_stocks 205) (candidates_after_held 198)
    (macro_trend Bullish) (long_macro_admitted 198)
    (long_breakout_admitted 24) (long_sector_admitted 24)
    (long_grade_admitted 24) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-12-13) (total_stocks 209) (candidates_after_held 203)
    (macro_trend Bullish) (long_macro_admitted 203)
    (long_breakout_admitted 17) (long_sector_admitted 17)
    (long_grade_admitted 17) (long_top_n_admitted 17)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-12-20) (total_stocks 211) (candidates_after_held 205)
    (macro_trend Bullish) (long_macro_admitted 205)
    (long_breakout_admitted 24) (long_sector_admitted 24)
    (long_grade_admitted 24) (long_top_n_admitted 20)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-12-27) (total_stocks 213) (candidates_after_held 206)
    (macro_trend Bullish) (long_macro_admitted 206)
    (long_breakout_admitted 14) (long_sector_admitted 14)
    (long_grade_admitted 14) (long_top_n_admitted 14)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0)))))
