((audit_records
  (((entry
     ((symbol AAPL) (entry_date 2019-06-21) (position_id AAPL-wein-2)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (621.8)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.017967958275741824) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.7052120350790312)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Information Technology") (sector_rating Strong)
      (cascade_score 65) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume"
        "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 211.17) (suggested_stop 194.2764)
      (installed_stop 163.4592) (stop_floor_kind Support_floor)
      (risk_pct 0.079999999999999974)
      (initial_position_value 125857.31999999999)
      (initial_risk_dollars 28435.636799999986) (alternatives_considered ())))
    (exit_ ()))
   ((entry
     ((symbol HD) (entry_date 2019-06-07) (position_id HD-wein-1)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Neutral) (weight 3)
         (detail "Index in Stage 1 base"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (581.8)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Neutral) (weight 1.5)
         (detail "Global markets mixed (0 bullish, 0 bearish)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0068226647205115428) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.7309637490948588)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name "Consumer Discretionary") (sector_rating Strong)
      (cascade_score 65) (cascade_grade B) (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume"
        "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 205.28)
      (suggested_stop 188.85760000000002) (installed_stop 178.8192)
      (stop_floor_kind Support_floor) (risk_pct 0.0799999999999999)
      (initial_position_value 124810.24)
      (initial_risk_dollars 16088.166400000004) (alternatives_considered ())))
    (exit_
     (((symbol HD) (exit_date 2019-12-11) (position_id HD-wein-1)
       (exit_trigger
        (Stop_loss (stop_price 210.71115) (actual_price 210.61)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage3 (weeks_topping 157))) (rs_trend_at_exit ())
       (distance_from_ma_pct -0.046072899185468356)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol JNJ) (entry_date 2019-06-21) (position_id JNJ-wein-3)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (621.8)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.006074377738586793) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.6924178646834949)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory)) (sector_name "Health Care")
      (sector_rating Neutral) (cascade_score 55) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume"
        "Virgin territory"))
      (side Long) (suggested_entry 149.73) (suggested_stop 137.7516)
      (installed_stop 146.375) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.07999999999999996) (initial_position_value 125922.93)
      (initial_risk_dollars 2821.5549999999912) (alternatives_considered ())))
    (exit_
     (((symbol JNJ) (exit_date 2019-06-24) (position_id JNJ-wein-3)
       (exit_trigger (Stop_loss (stop_price 146.375) (actual_price 142.09)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 2) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.0447763135686496)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol JNJ) (entry_date 2019-06-28) (position_id JNJ-wein-5)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (637.2)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 3) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.010250852330461436) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.6924178646834949)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory)) (sector_name "Health Care")
      (sector_rating Strong) (cascade_score 50) (cascade_grade C)
      (cascade_score_components ())
      (cascade_rationale
       ("Early Stage2" "Adequate volume" "Virgin territory" "Strong sector"))
      (side Long) (suggested_entry 149.73) (suggested_stop 137.7516)
      (installed_stop 146.375) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.07999999999999996)
      (initial_position_value 126072.65999999999)
      (initial_risk_dollars 2824.9099999999912) (alternatives_considered ())))
    (exit_
     (((symbol JNJ) (exit_date 2019-07-01) (position_id JNJ-wein-5)
       (exit_trigger (Stop_loss (stop_price 146.375) (actual_price 138.72)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 4) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.01718421957047038)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol JNJ) (entry_date 2019-11-29) (position_id JNJ-wein-6)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (736.5)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 1) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0058155502308307808) (rs_trend (Positive_flat))
      (rs_value (0.9495247382383194))
      (volume_quality ((Adequate 1.8438155585049449)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory)) (sector_name "Health Care")
      (sector_rating Strong) (cascade_score 75) (cascade_grade A)
      (cascade_score_components ())
      (cascade_rationale
       ("Stage1\226\134\146Stage2 breakout" "Adequate volume" "RS positive"
        "Virgin territory" "Strong sector"))
      (side Long) (suggested_entry 149.33)
      (suggested_stop 137.38360000000003) (installed_stop 146.223936)
      (stop_floor_kind Buffer_fallback) (risk_pct 0.079999999999999877)
      (initial_position_value 134695.66)
      (initial_risk_dollars 2801.669728000003) (alternatives_considered ())))
    (exit_
     (((symbol JNJ) (exit_date 2019-12-02) (position_id JNJ-wein-6)
       (exit_trigger
        (Stop_loss (stop_price 146.223936) (actual_price 136.85)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 2) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.042778089856102139)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol JNJ) (entry_date 2019-12-06) (position_id JNJ-wein-7)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (755.7)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 3) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0099716025631031938) (rs_trend (Positive_flat))
      (rs_value (0.970039773734496))
      (volume_quality ((Adequate 1.8438155585049449)))
      (resistance_quality (Virgin_territory))
      (support_quality (Virgin_territory)) (sector_name "Health Care")
      (sector_rating Strong) (cascade_score 60) (cascade_grade B)
      (cascade_score_components ())
      (cascade_rationale
       ("Early Stage2" "Adequate volume" "RS positive" "Virgin territory"
        "Strong sector"))
      (side Long) (suggested_entry 145.7) (suggested_stop 134.04399999999998)
      (installed_stop 142.66944) (stop_floor_kind Buffer_fallback)
      (risk_pct 0.080000000000000043)
      (initial_position_value 134918.19999999998)
      (initial_risk_dollars 2806.2985599999815) (alternatives_considered ())))
    (exit_
     (((symbol JNJ) (exit_date 2019-12-09) (position_id JNJ-wein-7)
       (exit_trigger
        (Stop_loss (stop_price 142.66944) (actual_price 140.06)))
       (macro_trend_at_exit Bullish) (macro_confidence_at_exit 1)
       (stage_at_exit (Stage2 (weeks_advancing 4) (late false)))
       (rs_trend_at_exit ()) (distance_from_ma_pct 0.060784416885129339)
       (max_favorable_excursion_pct 0) (max_adverse_excursion_pct 0)
       (weeks_macro_was_bearish 0) (weeks_stage_left_2 0)))))
   ((entry
     ((symbol JPM) (entry_date 2019-06-21) (position_id JPM-wein-4)
      (macro_trend Bullish) (macro_confidence 1)
      (macro_indicators
       (((name "Index Stage") (signal Bullish) (weight 3)
         (detail "Index in Stage 2 (advancing)"))
        ((name "A-D Line") (signal Bullish) (weight 2)
         (detail "A-D line confirming index advance"))
        ((name "Momentum Index") (signal Bullish) (weight 2)
         (detail "Momentum index positive (621.8)"))
        ((name NH-NL) (signal Bullish) (weight 1.5)
         (detail
          "Index trending higher over 3 months (NH-NL proxy positive)"))
        ((name "Global Markets") (signal Bullish) (weight 1.5)
         (detail "Global consensus bullish (2/3 markets Stage2)"))))
      (stage (Stage2 (weeks_advancing 2) (late false))) (ma_direction Rising)
      (ma_slope_pct 0.0096585137051661551) (rs_trend ()) (rs_value ())
      (volume_quality ((Adequate 1.5291406475304)))
      (resistance_quality (Clean)) (support_quality (Virgin_territory))
      (sector_name Financials) (sector_rating Strong) (cascade_score 50)
      (cascade_grade C) (cascade_score_components ())
      (cascade_rationale
       ("Early Stage2" "Adequate volume" "Clean overhead" "Strong sector"))
      (side Long) (suggested_entry 115.52) (suggested_stop 106.2784)
      (installed_stop 100.6464) (stop_floor_kind Support_floor)
      (risk_pct 0.079999999999999932) (initial_position_value 125916.8)
      (initial_risk_dollars 16212.223999999997) (alternatives_considered ())))
    (exit_ ()))))
 (cascade_summaries
  (((date 2018-11-09) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-16) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-23) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-11-30) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-07) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-14) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-21) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2018-12-28) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-04) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-11) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-18) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Neutral) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-01-25) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-01) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-08) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-15) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-02-22) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-01) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-08) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-15) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-22) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-03-29) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-05) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-12) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-04-26) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-03) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-10) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-17) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-24) (total_stocks 0) (candidates_after_held 0)
    (macro_trend Bullish) (long_macro_admitted 0) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-05-31) (total_stocks 1) (candidates_after_held 1)
    (macro_trend Bullish) (long_macro_admitted 1) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-06-07) (total_stocks 3) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 1)
    (long_sector_admitted 1) (long_grade_admitted 1) (long_top_n_admitted 1)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-06-14) (total_stocks 4) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-06-21) (total_stocks 6) (candidates_after_held 5)
    (macro_trend Bullish) (long_macro_admitted 5) (long_breakout_admitted 3)
    (long_sector_admitted 3) (long_grade_admitted 3) (long_top_n_admitted 3)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 3))
   ((date 2019-06-28) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 1)
    (long_sector_admitted 1) (long_grade_admitted 1) (long_top_n_admitted 1)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-07-05) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-07-12) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-07-19) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-07-26) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-02) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-09) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-16) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-23) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-08-30) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-06) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-13) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-20) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-09-27) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-04) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-11) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-18) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-10-25) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-01) (total_stocks 7) (candidates_after_held 4)
    (macro_trend Bullish) (long_macro_admitted 4) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-08) (total_stocks 5) (candidates_after_held 2)
    (macro_trend Bullish) (long_macro_admitted 2) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-15) (total_stocks 5) (candidates_after_held 2)
    (macro_trend Bullish) (long_macro_admitted 2) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-22) (total_stocks 5) (candidates_after_held 2)
    (macro_trend Bullish) (long_macro_admitted 2) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-11-29) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 1)
    (long_sector_admitted 1) (long_grade_admitted 1) (long_top_n_admitted 1)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-12-06) (total_stocks 6) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 1)
    (long_sector_admitted 1) (long_grade_admitted 1) (long_top_n_admitted 1)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 1))
   ((date 2019-12-13) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-12-20) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0))
   ((date 2019-12-27) (total_stocks 5) (candidates_after_held 3)
    (macro_trend Bullish) (long_macro_admitted 3) (long_breakout_admitted 0)
    (long_sector_admitted 0) (long_grade_admitted 0) (long_top_n_admitted 0)
    (short_macro_admitted 0) (short_breakdown_admitted 0)
    (short_sector_admitted 0) (short_rs_hard_gate_admitted 0)
    (short_grade_admitted 0) (short_top_n_admitted 0) (entered 0)))))
