(lang dune 3.17)

(name weinstein)

(generate_opam_files true)

(package
 (name weinstein)
 (allow_empty)
 (depends
  ocaml
  async
  base
  core
  ppx_deriving
  ppx_let
  status
  types
  csv
  eodhd
  indicators))
