(** Weinstein order generation.

    Converts screener output and stop events into concrete suggested orders.
    These orders represent what the weekly workflow would submit — entry
    stop-limit orders from screener candidates, stop adjustments from the
    trailing stop state machine, and exit market orders when stops are hit.

    {1 Design}

    Pure functions. No state. Every function takes its full context and returns
    a list of suggested orders. The caller (strategy or UI) decides what to do
    with them.

    Builds alongside (not replacing)
    [trading/simulation/lib/order_generator.ml], which converts
    [Position.transition] values to market orders. This module adds
    Weinstein-specific logic: grades, rationale text, and stop-limit entry
    orders from screener output. *)

open Trading_base.Types

(** {1 Types} *)

type suggested_order = {
  ticker : string;
  side : side;
      (** [Buy] for entries and stop raises; [Sell] for long exits; [Buy] for
          short exits (covering). *)
  order_type : order_type;
      (** [StopLimit] for new entries (buy above breakout + buffer). [Stop] for
          exits triggered by stop events. *)
  shares : int;  (** Number of shares suggested. Always positive. *)
  grade : Weinstein_types.grade option;
      (** Grade from screener, if this order came from a candidate. [None] for
          stop-driven orders. *)
  rationale : string list;
      (** Human-readable list of signals that justify this order. Derived from
          screener rationale for entries; from stop event reason for adjustments
          and exits. *)
}
[@@deriving show, eq]
(** A suggested order generated by the Weinstein weekly workflow. *)

(** {1 Generation Functions} *)

val from_candidates :
  candidates:Screener.scored_candidate list ->
  snapshot:Portfolio_risk.portfolio_snapshot ->
  config:Portfolio_risk.config ->
  suggested_order list
(** Generate entry orders for screener candidates that pass portfolio limits.

    For each candidate, compute the position size using fixed-risk sizing and
    the candidate's [suggested_entry] and [suggested_stop]. Exclude candidates
    that would violate any limit in [config] given the current [snapshot].

    Entry order type: [StopLimit (suggested_entry, suggested_entry)] — a
    buy-stop that triggers when price crosses the entry level.

    @param candidates Screener output (already ranked by score).
    @param snapshot Current portfolio state for limit checks.
    @param config Risk limits and sizing parameters.
    @return Suggested entry orders, in candidate rank order. *)

val from_stop_adjustments :
  adjustments:(string * Weinstein_stops.stop_event) list ->
  positions:Trading_strategy.Position.t Core.String.Map.t ->
  suggested_order list
(** Generate stop-order updates for positions whose stops were raised.

    For each [Stop_raised] event, suggest a replacement [Stop] order at the new
    level. [Stop_hit] and [No_change] events are ignored here — exits are
    handled by [from_exits].

    @param adjustments [(ticker, stop_event)] pairs from the stop state machine.
    @param positions Current open positions; used to determine side and shares.
    @return Stop update orders, one per [Stop_raised] event. *)

val from_exits :
  exits:(string * Weinstein_stops.stop_event) list ->
  positions:Trading_strategy.Position.t Core.String.Map.t ->
  suggested_order list
(** Generate market exit orders for positions that hit their stop.

    For each [Stop_hit] event, suggest a market order to close the position at
    the stop trigger price. [Stop_raised], [Entered_tightening], and [No_change]
    events are ignored.

    @param exits [(ticker, stop_event)] pairs from the stop state machine.
    @param positions Current open positions; used to determine side and shares.
    @return Market exit orders, one per [Stop_hit] event. *)
