open OUnit2
open Core
open Trading_engine
open Trading_engine.Types
open Matchers

(** Reproducibility contract for engine-level intraday paths.

    [market_state.mli] claims "same bar + scratch + config -> same path". Before
    the per-bar seed landed that sentence was false: [Price_path.default_config]
    carries [seed = None], which makes every generated path draw from
    [Random.State.make_self_init ()], so two identical runs of the same backtest
    binary produced different fill prices.

    The bug was invisible to every golden because a golden's orders are market
    orders, which fill at the bar's open/close and never consult the path. Only
    resting stop/limit orders walk it — i.e. exactly the armed-StopLimit entry
    family that no golden scenario arms. Measured on the 302-symbol
    goldens-small universe over six years, four runs of one binary returned
    49.2846 / 50.0589 / 49.3444 / 49.3723 percent. *)

let make_bar symbol ~open_price ~high_price ~low_price ~close_price =
  { symbol; open_price; high_price; low_price; close_price }

let a_bar =
  make_bar "AAPL" ~open_price:100.0 ~high_price:110.0 ~low_price:95.0
    ~close_price:105.0

(* A path generated by a market state freshly seeded with [bar] — a distinct
   [t] per call, so nothing is shared between the two paths under comparison
   except the bar itself. *)
let path_of_fresh_state ?(path_config = Price_path.default_config) bar =
  let t = Market_state.create () in
  Market_state.update t ~path_config [ bar ];
  Market_state.path_for t ~symbol:bar.symbol

let prices path = List.map path ~f:(fun (p : path_point) -> p.price)

let test_same_bar_same_path _ =
  let first = path_of_fresh_state a_bar in
  let second = path_of_fresh_state a_bar in
  assert_that
    (Option.map first ~f:prices)
    (is_some_and (equal_to (Option.value_exn (Option.map second ~f:prices))))

(* The seed must vary with the bar, or every bar in a run would share one noise
   shape — reproducible, but a degenerate path model. *)
let test_different_bars_differ _ =
  let other =
    make_bar "AAPL" ~open_price:100.0 ~high_price:130.0 ~low_price:80.0
      ~close_price:120.0
  in
  let a = Option.value_exn (path_of_fresh_state a_bar) |> prices in
  let b = Option.value_exn (path_of_fresh_state other) |> prices in
  assert_that (List.equal Float.equal a b) (equal_to false)

(* Same OHLC, different ticker: the seed is derived from the symbol too, so two
   symbols moving identically still get independent paths. *)
let test_different_symbols_differ _ =
  let twin = { a_bar with symbol = "MSFT" } in
  let a = Option.value_exn (path_of_fresh_state a_bar) |> prices in
  let b = Option.value_exn (path_of_fresh_state twin) |> prices in
  assert_that (List.equal Float.equal a b) (equal_to false)

(* An explicit [seed] is still honoured verbatim — the existing escape hatch for
   tests that want one fixed noise draw across every bar. *)
let test_explicit_seed_still_honoured _ =
  let path_config = { Price_path.default_config with seed = Some 42 } in
  let a = Option.value_exn (path_of_fresh_state ~path_config a_bar) |> prices in
  let b = Option.value_exn (path_of_fresh_state ~path_config a_bar) |> prices in
  assert_that a (equal_to b)

(* The memo already guaranteed one path per symbol per tick; pin it alongside
   the cross-run guarantee so a future seed change cannot quietly reintroduce
   per-call regeneration. *)
let test_repeated_calls_within_tick_memoized _ =
  let t = Market_state.create () in
  Market_state.update t ~path_config:Price_path.default_config [ a_bar ];
  let first = Market_state.path_for t ~symbol:"AAPL" in
  let second = Market_state.path_for t ~symbol:"AAPL" in
  assert_that
    (Option.map first ~f:prices)
    (is_some_and (equal_to (Option.value_exn (Option.map second ~f:prices))))

(* The salt selects a different path realisation without touching any decision
   rule. [0] must be bit-identical to the unsalted build, or every existing
   pinned number moves. *)
let test_salt_zero_matches_unsalted _ =
  assert_that
    (Price_path.seed_for_bar ~salt:0 a_bar)
    (equal_to (Price_path.seed_for_bar a_bar))

let test_nonzero_salt_changes_the_seed _ =
  assert_that
    (Price_path.seed_for_bar ~salt:1 a_bar = Price_path.seed_for_bar a_bar)
    (equal_to false)

(* Distinct salts must not collapse onto one realisation, or a K-salt sweep
   would silently measure the same draw K times. *)
let test_distinct_salts_stay_distinct _ =
  let seeds =
    List.map [ 1; 2; 3; 4; 5 ] ~f:(fun salt ->
        Price_path.seed_for_bar ~salt a_bar)
  in
  assert_that
    (List.length (List.dedup_and_sort seeds ~compare:Int.compare))
    (equal_to 5)

(* A salted seed is still a function of the bar: same salt + same bar => same
   seed, so a salted run is as reproducible as an unsalted one. *)
let test_salted_seed_is_reproducible _ =
  assert_that
    (Price_path.seed_for_bar ~salt:7 a_bar)
    (equal_to (Price_path.seed_for_bar ~salt:7 a_bar))

let test_unknown_symbol_is_none _ =
  let t = Market_state.create () in
  Market_state.update t ~path_config:Price_path.default_config [ a_bar ];
  assert_that (Market_state.path_for t ~symbol:"NVDA") is_none

let suite =
  "market_state"
  >::: [
         "same bar reproduces the same path across runs"
         >:: test_same_bar_same_path;
         "different bars get different paths" >:: test_different_bars_differ;
         "different symbols get different paths"
         >:: test_different_symbols_differ;
         "explicit seed is still honoured" >:: test_explicit_seed_still_honoured;
         "repeated calls within a tick are memoized"
         >:: test_repeated_calls_within_tick_memoized;
         "unknown symbol has no path" >:: test_unknown_symbol_is_none;
         "salt 0 is bit-identical to unsalted"
         >:: test_salt_zero_matches_unsalted;
         "a non-zero salt changes the seed"
         >:: test_nonzero_salt_changes_the_seed;
         "distinct salts stay distinct" >:: test_distinct_salts_stay_distinct;
         "a salted seed is reproducible" >:: test_salted_seed_is_reproducible;
       ]

let () = run_test_tt_main suite
