(** Render the deep multi-decade "results-of-record" headline block from a small
    file of {b pinned} records — never by recomputing.

    The heavy broad-universe backtests (top-3000, out-of-repo warehouse) cannot
    be regenerated by CI the way {!Toplines_runner} regenerates the light
    reference strategies. Their headline numbers are curated by hand in
    [dev/backtest/DEEP_RESULTS.md] and mirrored, machine-readable, into
    [dev/backtest/deep_headline_records.sexp]. This module reads that sexp and
    renders it into the README's [<!-- deep-headline:start -->] block — pure
    string work, no backtest execution. Each record pins its scenario sexp + the
    commit it was measured at so the number is auditable. *)

type record = {
  label : string;  (** Human-readable row label, e.g. the config / sleeve. *)
  total_return_pct : float;
      (** Total return % over {!field:period} (mark-to-market basis; see the
          rendered caveat). *)
  max_drawdown_pct : float option; [@sexp.option]
      (** Max drawdown %; [None] (rendered ["—"]) for comparator rows that do
          not carry one. *)
  trades : int option; [@sexp.option]
      (** Number of round-trip trades; [None] for comparator rows. *)
  win_rate_pct : float option; [@sexp.option]
      (** Win rate %; [None] when not pinned in the source record. *)
  period : string;  (** Inclusive window, e.g. ["2000-01-01 -> 2026-06-26"]. *)
  scenario_path : string;
      (** Repo-relative scenario sexp the number was measured from (may live in
          an out-of-repo / gitignored staging area — it is a citation, not a
          runnable-in-CI path), or a short comparator note. *)
  basis_commit : string;
      (** The commit (and/or PR) the measurement was taken at, plus any basis
          note (warehouse, ledger entry). *)
  date : string;  (** Measurement date, ISO ["YYYY-MM-DD"]. *)
}
[@@deriving sexp]
(** One pinned headline row. Optional numeric fields render as ["—"] so a
    benchmark comparator (total return + period only) coexists with a full
    strategy record. *)

val start_marker : string
(** [<!-- deep-headline:start -->] — opening sentinel for the deep block. *)

val end_marker : string
(** [<!-- deep-headline:end -->] — closing sentinel for the deep block. *)

val load : string -> record list option
(** [load path] reads the pinned records from the sexp file at [path]. The file
    is a {e sequence} of top-level [(record …)] sexps (one per row; blank lines
    and [;] comments between them are fine), in render order.

    - [Some records] when the file exists and parses.
    - [None] when the file does {e not} exist — the caller skips the block with
      a warning rather than crashing (the README's existing deep block, if any,
      is left untouched).

    @raise Failure
      when the file exists but is malformed (a defect in checked-in data, not a
      skip-worthy condition). *)

val render_markdown : record list -> string
(** [render_markdown records] is the inner body of the deep block (without the
    {!start_marker}/{!end_marker} lines): a header line, a metrics table (one
    row per record, optional fields shown as ["—"]), a per-row citation list
    (scenario + commit + date), and the standing MTM / realized-vs-MTM /
    liquidity caveat line. *)

val render_block : record list -> string
(** [render_block records] is {!render_markdown} wrapped between
    {!start_marker}/{!end_marker} via {!Readme_block.render_between} — the full
    block ready to hand to {!Readme_block.upsert_between}. *)
