((schema_version 1) (system_version 58ff1e79) (date 2026-06-12)
 (macro ((regime Bearish) (score 0)))
 (sectors_strong
  (Industrials "Information Technology" Materials "Real Estate"))
 (sectors_weak ()) (long_candidates ())
 (short_candidates
  (((symbol ABG) (score 50) (grade C) (entry 275.87)
    (stop 297.93960000000004) (sector "Consumer Discretionary")
    (rationale "Early Stage4; Strong breakdown volume; Clean support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol ABR) (score 50) (grade C) (entry 12.64) (stop 13.651200000000001)
    (sector Financials)
    (rationale "Early Stage4; Strong breakdown volume; Clean support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol ADMA) (score 50) (grade C) (entry 20.56) (stop 22.2048)
    (sector "Health Care")
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol ADT) (score 50) (grade C) (entry 8.98) (stop 9.6984000000000012)
    (sector "Consumer Discretionary")
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol AHCO) (score 50) (grade C) (entry 12.93)
    (stop 13.964400000000001) (sector "Health Care")
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Clean)))
   ((symbol AIG) (score 50) (grade C) (entry 87.73) (stop 94.7484)
    (sector Financials)
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol ALHC) (score 50) (grade C) (entry 23.99) (stop 25.9092)
    (sector "Health Care")
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol AMPH) (score 50) (grade C) (entry 31.42)
    (stop 33.933600000000006) (sector "Health Care")
    (rationale "Early Stage4; Strong breakdown volume; Clean support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol AMRN) (score 50) (grade C) (entry 21) (stop 22.68)
    (sector "Health Care")
    (rationale "Early Stage4; Strong breakdown volume; Virgin support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))
   ((symbol AN) (score 50) (grade C) (entry 230.06) (stop 248.46480000000003)
    (sector "Consumer Discretionary")
    (rationale "Early Stage4; Strong breakdown volume; Clean support below")
    (rs_vs_spy ()) (resistance_grade (Weinstein_types.Virgin_territory)))))
 (held_positions ()))
