;; perf-tier: 3-historical
;; perf-tier-rationale: 15y sp500 historical backtest with survivorship-aware
;; universe (510 symbols from universes/sp500-historical/sp500-2010-01-01.sexp,
;; built via Wiki+EODHD replay PR-A/B/C #803/#808/#809). Window 2010-01-01 →
;; 2026-04-30 spans the full post-2010 cycle: post-GFC recovery, 2011 sideways,
;; 2015-16 correction, 2018 Q4 drawdown, COVID crash + recovery, 2022 bear,
;; 2023-25 advance.
;;
;; **STATUS**: SCAFFOLDING. First run on 2026-05-03 used the wrong invocation
;; (no --universe-path flag, defaulted to data/sectors.csv broad → 0 trades).
;; This scenario sexp is the canonical fix — invoke via scenario_runner.exe
;; --dir goldens-sp500-historical/. See `dev/notes/15y-sp500-zero-trades-
;; diagnosis-2026-05-03.md`.
;;
;; **Survivorship handling**: `sp500-2010-01-01.sexp` was generated by
;; `Membership_replay.replay_back ~as_of:2010-01-01` from the 2026-05-03
;; Wikipedia changes table snapshot. 510 symbols with sectors carried from
;; the current S&P 500 constituent table; symbols re-added via reverse
;; replay carry sector="Unknown" (174 of 510). Strategy may filter Unknown-
;; sector symbols at the screener layer — accept this as a known limitation
;; for the v1 historical backtest. See plan §"Sector drift during the window"
;; in `dev/plans/wiki-eodhd-historical-universe-2026-05-03.md`.
;;
;; **Wide expected ranges** (BASELINE_PENDING): expected ranges are
;; intentionally permissive until the first successful run lands real
;; numbers. Tighten via follow-up PR after the run.
((name "sp500-2010-2026-historical")
 (description
   "15y sp500 historical backtest — survivorship-aware universe (510 symbols, replayed back to 2010-01-01), 2010-01-01 → 2026-04-30. Companion to goldens-sp500/sp500-2019-2023.sexp's 5y window.")
 (period ((start_date 2010-01-01) (end_date 2026-04-30)))
 (universe_path "universes/sp500-historical/sp500-2010-01-01.sexp")
 (universe_size 510)
 ;; enable_short_side disabled mirroring the existing sp500-2019-2023 +
 ;; goldens-broad/decade-2014-2023 cells (G1-G4 short-side gaps unresolved per
 ;; dev/notes/short-side-gaps-2026-04-29.md).
 (config_overrides (((enable_short_side false))))
 ;; PINNED_AFTER_FIRST_RUN — wide ranges. First successful run on the
 ;; user's 8 GB box under snapshot mode produces the canonical baseline.
 (expected
  ((total_return_pct   ((min -1000.0)        (max 1000000.0)))
   (total_trades       ((min 0)              (max 100000)))
   (win_rate           ((min 0.0)            (max 100.0)))
   (sharpe_ratio       ((min -10.0)          (max 10.0)))
   (max_drawdown_pct   ((min 0.0)            (max 100.0)))
   (avg_holding_days   ((min 0.0)            (max 10000.0)))
   (open_positions_value ((min -1000000000.0) (max 100000000000.0))))))
