;; perf-tier: 3-historical
;; perf-tier-rationale: 15y sp500 historical backtest with survivorship-aware
;; universe (510 symbols from universes/sp500-historical/sp500-2010-01-01.sexp,
;; built via Wiki+EODHD replay PR-A/B/C #803/#808/#809). Window 2010-01-01 →
;; 2026-04-30 spans the full post-2010 cycle: post-GFC recovery, 2011 sideways,
;; 2015-16 correction, 2018 Q4 drawdown, COVID crash + recovery, 2022 bear,
;; 2023-25 advance.
;;
;; **STATUS**: SCAFFOLDING. First run on 2026-05-03 used the wrong invocation
;; (no --universe-path flag, defaulted to data/sectors.csv broad → 0 trades).
;; This scenario sexp is the canonical fix — invoke via scenario_runner.exe
;; --dir goldens-sp500-historical/. See `dev/notes/15y-sp500-zero-trades-
;; diagnosis-2026-05-03.md`.
;;
;; **Survivorship handling**: `sp500-2010-01-01.sexp` was generated by
;; `Membership_replay.replay_back ~as_of:2010-01-01` from the 2026-05-03
;; Wikipedia changes table snapshot. 510 symbols with sectors carried from
;; the current S&P 500 constituent table; symbols re-added via reverse
;; replay carry sector="Unknown" (174 of 510). Strategy may filter Unknown-
;; sector symbols at the screener layer — accept this as a known limitation
;; for the v1 historical backtest. See plan §"Sector drift during the window"
;; in `dev/plans/wiki-eodhd-historical-universe-2026-05-03.md`.
;;
;; **Wide expected ranges** (BASELINE_PENDING): expected ranges are
;; intentionally permissive until the first successful run lands real
;; numbers. Tighten via follow-up PR after the run.
((name "sp500-2010-2026-historical")
 (description
   "15y sp500 historical backtest — survivorship-aware universe (510 symbols, replayed back to 2010-01-01), 2010-01-01 → 2026-04-30. Companion to goldens-sp500/sp500-2019-2023.sexp's 5y window.")
 (period ((start_date 2010-01-01) (end_date 2026-04-30)))
 (universe_path "universes/sp500-historical/sp500-2010-01-01.sexp")
 (universe_size 510)
 ;; enable_short_side disabled mirroring the existing sp500-2019-2023 +
 ;; goldens-broad/decade-2014-2023 cells (G1-G4 short-side gaps unresolved per
 ;; dev/notes/short-side-gaps-2026-04-29.md).
 ;;
 ;; Position-sizing overrides per dev/notes/15y-trade-count-investigation-2026-05-05.md
 ;; (PR #853 root-cause). Default sizing was calibrated against the 5y
 ;; sp500-2019-2023 baseline; on a 15y window with 510 symbols + only $1M
 ;; initial cash, the 0.30/0.90/0.10 defaults caused day-1 to lock up
 ;; ~$993K across 4 oversized positions, with 8 long-runners pinning
 ;; ~$949K cost basis for ~15 years. Skip ratio measured 271
 ;; Insufficient_cash : 37 Stop_too_wide (7.3:1). The override below
 ;; widens the entry funnel proportional to the window's longer horizon
 ;; without modifying the default Portfolio_risk.config (which other
 ;; goldens depend on).
 ;; Cell E rollout 2026-05-11: position sizing promoted from 0.05/0.50/0.30 to
 ;; 0.14/0.70/0.30 AND stage3 force-exit (h=1) + laggard rotation (h=2) added
 ;; for full Cell E parity. Single canonical strategy config across all
 ;; goldens. Prior 0.05/0.50 baseline (110.84% / 302 trades / 23.3% DD) and
 ;; the partial 0.14/0.70-without-rotation baseline (594.35% / 40 trades /
 ;; 28.4% DD) both preserved in git history.
 ;; Measured 2026-05-13 (full Cell E, 16.3y window, post-#1052 force-liq fix
 ;; + #1053/#1054 schema):
 ;;   total_return_pct  341.69  total_trades  806  win_rate 39.08
 ;;   sharpe_ratio       0.78   max_drawdown 18.36 avg_holding_days  44.68
 ;;   open_positions_value 3,085,413  unrealized_pnl 566,200
 ;;   sortino_ratio_annualized 1.25   calmar_ratio 0.52   ulcer_index 7.48
 ;;   force_liquidations_count 10
 ;;
 ;; Pre-P1-fix (2026-05-11) vs post-P1-fix delta:
 ;;   return    344.9  → 341.69  (-0.9%, marginal)
 ;;   trades   1099    → 806     (-27%, P1 prevents spurious cascade churn)
 ;;   avg_hold  34     → 44.68   (+31%, positions live longer without
 ;;                                weekly forced exits)
 ;;   force-liqs  0    → 10      (1 legitimate cascade × ~10 positions —
 ;;                                same root mechanism as long-short, see
 ;;                                dev/notes/longshort-cascades-investigation-2026-05-13.md)
 ;; Cell E rotation cuts MaxDD by 10pp vs the no-rotation 0.14/0.70 variant
 ;; (28 → 18.4) while running 22x more trades (40 → 806). Tolerances ±15%.
 (config_overrides
  (((enable_short_side false))
   ((portfolio_config ((max_position_pct_long 0.14))))
   ((portfolio_config ((max_long_exposure_pct 0.70))))
   ((portfolio_config ((min_cash_pct 0.30))))
   ((enable_stage3_force_exit true))
   ((stage3_force_exit_config ((hysteresis_weeks 1))))
   ((enable_laggard_rotation true))
   ((laggard_rotation_config ((hysteresis_weeks 2))))))
 ;; Re-pinned 2026-05-13 post NAV stale-price fix (#1063). Long-only
 ;; force_liq events on this 16y run: 0 (vs spurious events pre-fix).
 ;; The Portfolio_view avg-cost fallback removes the phantom NAV
 ;; collapse → Peak_tracker no longer fires on gapped-data days, so
 ;; the realistic-mtm path opens more positions and holds them longer.
 ;; open_positions_value drifts ~12% higher; total_trades drifts a
 ;; few units lower as fewer false-exit cycles trigger. Wall on local
 ;; parallel-3 in trading-1-dev: 1218.7s; pin sized to absorb GHA/local
 ;; variance.
 (expected
  ((total_return_pct   ((min 290.0)         (max 393.0)))
   (total_trades       ((min 640)           (max  800)))
   (win_rate           ((min  33.2)         (max  44.9)))
   (sharpe_ratio       ((min   0.66)        (max   0.90)))
   (max_drawdown_pct   ((min  15.6)         (max  21.2)))
   (avg_holding_days   ((min  37.9)         (max  51.3)))
   (open_positions_value ((min 3400000.0)   (max 4400000.0)))
   (sortino_ratio_annualized ((min  1.06)   (max   1.43)))
   (calmar_ratio       ((min   0.44)        (max   0.59)))
   (ulcer_index        ((min   6.35)        (max   8.60)))
   (wall_seconds       ((min 600.0)         (max 2400.0))))))
