(** Regenerate the [data/expected_universe_2010-01-01.sexp] golden by running
    [Membership_replay.replay_back] on the pinned 2026-05-03 snapshots.

    Run on demand:
    {v
    dune exec analysis/data/sources/wiki_sp500/test/gen_golden_2010_universe.exe
    v}

    Output is written relative to [test/data/]. The companion test
    [test_membership_replay.test_replay_back_to_2010_01_01_cardinality] keeps
    the golden honest by asserting cardinality bounds. *)

open Core

let _csv_path = "./data/current_constituents_2026-05-03.csv"
let _html_path = "./data/changes_table_2026-05-03.html"
let _golden_path = "./data/expected_universe_2010-01-01.sexp"

let _read_or_die path =
  try In_channel.read_all path
  with Sys_error msg -> failwith (Printf.sprintf "read %s: %s" path msg)

let () =
  let csv = _read_or_die _csv_path in
  let html = _read_or_die _html_path in
  let current =
    match Wiki_sp500.Membership_replay.parse_current_csv csv with
    | Ok cs -> cs
    | Error e -> failwith ("CSV parse: " ^ Status.show e)
  in
  let changes =
    match Wiki_sp500.Changes_parser.parse html with
    | Ok evs -> evs
    | Error e -> failwith ("HTML parse: " ^ Status.show e)
  in
  let as_of = Date.create_exn ~y:2010 ~m:Month.Jan ~d:1 in
  let result =
    match Wiki_sp500.Membership_replay.replay_back ~current ~changes ~as_of with
    | Ok cs -> cs
    | Error e -> failwith ("replay: " ^ Status.show e)
  in
  let sexp = Wiki_sp500.Membership_replay.to_universe_sexp result in
  Out_channel.with_file _golden_path ~f:(fun oc ->
      Out_channel.output_string oc
        ";; Golden universe for 2010-01-01, generated by\n\
         ;;   Membership_replay.replay_back ~as_of:2010-01-01\n\
         ;; from pinned 2026-05-03 snapshots:\n\
         ;;   data/current_constituents_2026-05-03.csv (Wikipedia main \
         constituents table)\n\
         ;;   data/changes_table_2026-05-03.html (Wikipedia changes table)\n\
         ;;\n";
      Out_channel.output_string oc
        (Printf.sprintf ";; Cardinality: %d constituents.\n"
           (List.length result));
      Out_channel.output_string oc
        ";; Sectors are \"Unknown\" for re-added (delisted-since) symbols —\n\
         ;; point-in-time GICS sectors are not tracked (plan §Out).\n\
         ;;\n\
         ;; To regenerate:\n\
         ;;   dune exec \
         analysis/data/sources/wiki_sp500/test/gen_golden_2010_universe.exe\n\n";
      Sexp.output_hum oc sexp;
      Out_channel.output_string oc "\n");
  Printf.printf "Wrote %s with %d constituents\n" _golden_path
    (List.length result)
