(** Tests for [Build_universe_lib]. The CLI in [bin/build_universe.ml] is a thin
    wrapper not worth subprocess plumbing. The 2010-01-01 universe differs from
    PR-B's golden by exactly the seven post-2010 renames in
    [Ticker_aliases.all]: META↔FB, ELV↔ANTM, VTRS↔MYL, RTX↔UTX, DOW↔DWDP,
    LIN↔PX, BKNG↔PCLN. Cardinality is preserved. *)

open Core
open OUnit2
open Matchers

let _pinned_csv_path = "./data/current_constituents_2026-05-03.csv"
let _pinned_html_path = "./data/changes_table_2026-05-03.html"
let _pr_b_golden_path = "./data/expected_universe_2010-01-01.sexp"
let _date_2010_01_01 = Date.create_exn ~y:2010 ~m:Month.Jan ~d:1

let _empty_html =
  "<html><body><table id=\"changes\"><tr></tr></table></body></html>"

let _empty_cache_dir () = Core_unix.mkdtemp "/tmp/wiki_sp500_test_cache_"

let _write_to_temp ~contents ~suffix =
  let path = Filename_unix.temp_file "wiki_sp500_test" suffix in
  Out_channel.write_all path ~data:contents;
  path

let _run_offline_exn ~as_of ~current_csv ~html ~cache_dir =
  let csv_path = _write_to_temp ~contents:current_csv ~suffix:".csv" in
  let html_path = _write_to_temp ~contents:html ~suffix:".html" in
  match
    Build_universe_lib.run_offline ~as_of ~current_csv_path:csv_path
      ~wiki_html_path:html_path ~cache_dir
  with
  | Ok outcome -> outcome
  | Error err -> assert_failure ("run_offline failed: " ^ Status.show err)

let _symbols_of_universe_sexp = function
  | Sexp.List [ _; Sexp.List es ] ->
      List.filter_map es ~f:(function
        | Sexp.List [ Sexp.List [ _; Sexp.Atom sym ]; Sexp.List [ _; _ ] ] ->
            Some sym
        | _ -> None)
      |> String.Set.of_list
  | _ -> assert_failure "unexpected universe sexp shape"

(* PR-B's golden was generated by replay without canonicalization; this
   CLI canonicalizes on top, so the diff is exactly the seven post-2010
   renames listed in the module docstring. *)
let _expected_pre_rename = [ "ANTM"; "DWDP"; "FB"; "MYL"; "PCLN"; "PX"; "UTX" ]

let _expected_post_rename =
  [ "BKNG"; "DOW"; "ELV"; "LIN"; "META"; "RTX"; "VTRS" ]

let test_smoke_build_universe_2010_01_01_no_fetch _ =
  let outcome =
    match
      Build_universe_lib.run_offline ~as_of:_date_2010_01_01
        ~current_csv_path:_pinned_csv_path ~wiki_html_path:_pinned_html_path
        ~cache_dir:(_empty_cache_dir ())
    with
    | Ok o -> o
    | Error e -> assert_failure ("run_offline: " ^ Status.show e)
  in
  let cli_symbols = _symbols_of_universe_sexp outcome.universe_sexp in
  let pr_b_symbols =
    _symbols_of_universe_sexp (Sexp.load_sexp _pr_b_golden_path)
  in
  assert_that
    (Set.length cli_symbols, Set.length pr_b_symbols)
    (pair (equal_to 510) (equal_to 510));
  assert_that
    ( Set.to_list (Set.diff cli_symbols pr_b_symbols),
      Set.to_list (Set.diff pr_b_symbols cli_symbols) )
    (pair (equal_to _expected_pre_rename) (equal_to _expected_post_rename))

(* Synthetic single-symbol CSV + empty cache dir → exactly one warning. *)
let test_emits_warning_when_local_csv_missing _ =
  let outcome =
    _run_offline_exn ~as_of:_date_2010_01_01
      ~current_csv:"Symbol,Security,GICS Sector\nFOO,Foo Corp,Industrials\n"
      ~html:_empty_html ~cache_dir:(_empty_cache_dir ())
  in
  assert_that outcome.warnings
    (elements_are
       [
         all_of
           [
             field
               (fun (w : Build_universe_lib.warning) -> w.symbol)
               (equal_to "FOO");
             field
               (fun (w : Build_universe_lib.warning) -> w.reason)
               (equal_to "no local bars");
           ];
       ])

(* Output sexp shape must match the canonical [universes/sp500.sexp]
   layout: [(Pinned (((symbol XXX) (sector "...")) ...))]. *)
let test_universe_sexp_shape_matches_canonical _ =
  let outcome =
    _run_offline_exn ~as_of:_date_2010_01_01
      ~current_csv:
        "Symbol,Security,GICS Sector\n\
         AAPL,Apple Inc.,Information Technology\n\
         XOM,Exxon Mobil,Energy\n"
      ~html:_empty_html ~cache_dir:(_empty_cache_dir ())
  in
  let expected =
    Sexp.of_string
      "(Pinned (((symbol AAPL) (sector \"Information Technology\")) ((symbol \
       XOM) (sector Energy))))"
  in
  assert_that outcome.universe_sexp (equal_to expected)

(* CP4 pin: [run_with_fetch]'s docstring claims (a) auto-fetch on cache miss and
   (b) 404-return → symbol skipped + omitted from universe_sexp. The [?fetch]
   hook in the .mli is "for tests" — exercise it. *)
let test_fetch_hook_pins_auto_fetch_and_404_skip _ =
  let valid_json =
    {|[{"date":"2010-01-04","open":10.0,"high":10.5,"low":9.8,"close":10.25,"adjusted_close":10.25,"volume":100000},{"date":"2010-01-05","open":10.3,"high":10.7,"low":10.1,"close":10.55,"adjusted_close":10.55,"volume":110000}]|}
  in
  let fetch (uri : Uri.t) : string Status.status_or Async.Deferred.t =
    let path = Uri.path uri in
    Async.return
      (if String.is_substring path ~substring:"BAR" then Ok valid_json
       else if String.is_substring path ~substring:"FOO" then
         Error (Status.internal_error "HTTP 404: Not Found")
       else Ok valid_json)
  in
  let csv_path =
    _write_to_temp
      ~contents:
        "Symbol,Security,GICS Sector\n\
         BAR,Bar Holdings,Industrials\n\
         FOO,Foo Corp,Industrials\n"
      ~suffix:".csv"
  in
  let html_path = _write_to_temp ~contents:_empty_html ~suffix:".html" in
  let cache_dir = _empty_cache_dir () in
  let outcome =
    match
      Async.Thread_safe.block_on_async_exn (fun () ->
          Build_universe_lib.run_with_fetch ~as_of:_date_2010_01_01
            ~current_csv_path:csv_path ~wiki_html_path:html_path ~cache_dir
            ~token:"test-token" ~fetch ())
    with
    | Ok o -> o
    | Error e -> assert_failure ("run_with_fetch: " ^ Status.show e)
  in
  let symbols = _symbols_of_universe_sexp outcome.universe_sexp in
  assert_that outcome.fetched_count (equal_to 1);
  assert_that outcome.skipped
    (elements_are
       [
         all_of
           [
             field
               (fun (w : Build_universe_lib.warning) -> w.symbol)
               (equal_to "FOO");
             field
               (fun (w : Build_universe_lib.warning) -> w.reason)
               (matching
                  (fun reason ->
                    if String.is_substring reason ~substring:"404" then Some ()
                    else None)
                  ~msg:"reason mentions 404" (equal_to ()));
           ];
       ]);
  assert_that (Set.mem symbols "BAR") (equal_to true);
  assert_that (Set.mem symbols "FOO") (equal_to false)

let suite =
  "build_universe_test"
  >::: [
         "smoke_build_universe_2010_01_01_no_fetch"
         >:: test_smoke_build_universe_2010_01_01_no_fetch;
         "emits_warning_when_local_csv_missing"
         >:: test_emits_warning_when_local_csv_missing;
         "universe_sexp_shape_matches_canonical"
         >:: test_universe_sexp_shape_matches_canonical;
         "fetch_hook_pins_auto_fetch_and_404_skip"
         >:: test_fetch_hook_pins_auto_fetch_and_404_skip;
       ]

let () = run_test_tt_main suite
