open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let ta_initialize = foreign "TA_Initialize" (void @-> returning int)
  let ta_shutdown = foreign "TA_Shutdown" (void @-> returning int)
  let ta_sma = foreign "TA_SMA"
    (int @-> int @-> ptr double @-> int @-> ptr double @-> ptr int @-> ptr int @-> returning int)
  let ta_ema = foreign "TA_EMA"
    (int @-> int @-> ptr double @-> int @-> ptr double @-> ptr int @-> ptr int @-> returning int)
  let ta_rsi = foreign "TA_RSI"
    (int @-> int @-> ptr double @-> int @-> ptr double @-> ptr int @-> ptr int @-> returning int)
end
