(lang dune 3.17)

(name trading)
(version 0.1.0)

(generate_opam_files true)

(package
 (name trading)
 (depends
  ocaml core
  ppx_deriving))

(package
 (name weinstein_trading)
 (allow_empty)
 (depends
  ocaml core
  ppx_deriving
  weinstein))
